package com.home.springtest.model;

import java.util.Date;

/**
 * Employee4 generated by hbm2java
 */
public class Employee4 implements java.io.Serializable {

	private int id;
	private String name;
	private Date updatedate;
	private Boolean status;
	private int level;

	public Employee4() {
	}

	public Employee4(int id) {
		this.id = id;
	}

	public Employee4(int id, String name, Date updatedate, int level) {
		this.id = id;
		this.name = name;
		this.updatedate = updatedate;
		this.level = level;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public Boolean getStatus() {
		return status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

}
