package com.home.springtest.model;

import java.util.Date;

/**
 * Employee3 generated by hbm2java
 */
public class Employee3 implements java.io.Serializable {

	private int id;
	private String name;
	private Date updatedate;
	private int departure;

	public Employee3() {
	}

	public Employee3(int id) {
		this.id = id;
	}

	public Employee3(int id, String name, Date updatedate, int departure) {
		this.id = id;
		this.name = name;
		this.updatedate = updatedate;
		this.setDeparture(departure);
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	public int getDeparture() {
		return departure;
	}

	public void setDeparture(int departure) {
		this.departure = departure;
	}

}
