package com.home.springtest.model;

import java.util.Date;

/**
 * Employee1 generated by hbm2java
 */
public class Employee1 implements java.io.Serializable {

	private int id;
	private String name;
	private Date updatedate;

	public Employee1() {
	}

	public Employee1(int id) {
		this.id = id;
	}

	public Employee1(int id, String name, Date updatedate) {
		this.id = id;
		this.name = name;
		this.updatedate = updatedate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}
}
